services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tresoresathub
      POSTGRES_PASSWORD: tresoresathub16
      POSTGRES_DB: esathub
    ports:
      - "5432:5432"
