services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user_esathub
      POSTGRES_PASSWORD: password_user_esathub
      POSTGRES_DB: esathub
    ports:
      - "5432:5432"
