"""room relationship on course session table

Revision ID: 00cb0c3ab964
Revises: 08e90537c7df
Create Date: 2026-06-07 11:19:27.088905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cb0c3ab964'
down_revision: Union[str, Sequence[str], None] = '08e90537c7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_sessions', sa.Column('room_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'course_sessions', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_sessions', type_='foreignkey')
    op.drop_column('course_sessions', 'room_id')
    # ### end Alembic commands ###
