"""make fields nullable

Revision ID: 065f7b7e8ca3
Revises: e7bd569350b3
Create Date: 2026-03-04 17:13:42.801069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '065f7b7e8ca3'
down_revision: Union[str, Sequence[str], None] = 'e7bd569350b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_type',
               existing_type=postgresql.ENUM('PHOTO', 'DOCUMENT', name='posttype'),
               nullable=True)
    op.alter_column('posts', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('posts', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('posts', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('posts', 'post_type',
               existing_type=postgresql.ENUM('PHOTO', 'DOCUMENT', name='posttype'),
               nullable=False)
    # ### end Alembic commands ###
