"""creation des tables pour les présences aux cours

Revision ID: 08e90537c7df
Revises: 139f29cdb907
Create Date: 2026-06-07 08:43:36.798727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08e90537c7df'
down_revision: Union[str, Sequence[str], None] = '139f29cdb907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'CLOSED', name='sessionstatus').create(op.get_bind())
    op.create_table('course_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('session_author_id', sa.UUID(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'CLOSED', name='sessionstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_records')
    op.drop_table('course_sessions')
    sa.Enum('ACTIVE', 'CLOSED', name='sessionstatus').drop(op.get_bind())
    # ### end Alembic commands ###
