"""add is_rep field to users table

Revision ID: 10cdcf5c91a9
Revises: 00cb0c3ab964
Create Date: 2026-06-07 13:01:24.483906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cdcf5c91a9'
down_revision: Union[str, Sequence[str], None] = '00cb0c3ab964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_romm_rep', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_romm_rep')
    # ### end Alembic commands ###
