"""Ajout d'un champ a la table media pour les teacher

Revision ID: 140d3e375338
Revises: fcb6c18c1030
Create Date: 2026-07-28 16:40:14.384681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140d3e375338'
down_revision: Union[str, Sequence[str], None] = 'fcb6c18c1030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('from_teacher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'from_teacher')
    # ### end Alembic commands ###
