"""add is_rep field to users table

Revision ID: 2420794bd63e
Revises: 10cdcf5c91a9
Create Date: 2026-06-07 13:31:51.258750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2420794bd63e'
down_revision: Union[str, Sequence[str], None] = '10cdcf5c91a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_room_rep', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.drop_column('users', 'is_romm_rep')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_romm_rep', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_room_rep')
    # ### end Alembic commands ###
