"""ajout du champ titre a la table notification

Revision ID: 268dce7c7189
Revises: ec26121880ac
Create Date: 2026-06-25 15:57:03.958538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268dce7c7189'
down_revision: Union[str, Sequence[str], None] = 'ec26121880ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
