"""ajout de la table room et ses relations

Revision ID: 2eac1e9e28d9
Revises: ca58626fe51d
Create Date: 2026-04-14 21:27:52.450103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eac1e9e28d9'
down_revision: Union[str, Sequence[str], None] = 'ca58626fe51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Créer la table rooms
    op.create_table(
        'rooms',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.Enum('PREPA_1', 'PREPA_2', 'INGE_1', 'INGE_2', 'INGE_3', name='roomnames'), nullable=False),
        sa.Column('rep_id', sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=False)

    # 2. Ajouter la colonne et la FK dans users
    op.add_column('users', sa.Column('user_room_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_users_room', 'users', 'rooms', ['user_room_id'], ['id'])
    op.create_index(op.f('ix_users_user_room_id'), 'users', ['user_room_id'], unique=False)

    # 3. Ajouter la FK pour le délégué (rep_id) dans rooms vers users
    op.create_foreign_key('fk_rooms_rep', 'rooms', 'users', ['rep_id'], ['id'])

    # 4. Ajouter la colonne et la FK dans posts (si tu veux lier les posts aux rooms)
    op.add_column('posts', sa.Column('room_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_posts_room', 'posts', 'rooms', ['room_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_user_room_id'), table_name='users')
    op.drop_column('users', 'user_room_id')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'room_id')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
