"""add avatar_path to users

Revision ID: 76d0103e397f
Revises: 065f7b7e8ca3
Create Date: 2026-03-15 14:33:51.410957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d0103e397f'
down_revision: Union[str, Sequence[str], None] = '065f7b7e8ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###
