"""ajout de plus d'option pour les spécialités

Revision ID: a2a78a28e281
Revises: 0f4d86e093d2
Create Date: 2026-05-12 17:16:30.788934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'a2a78a28e281'
down_revision: Union[str, Sequence[str], None] = '0f4d86e093d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='major',
        new_values=['IA', 'CYBERSECURITE', 'GENIE LOGICIEL', 'GENIE MECANIQUE', 'DATA SCIENCE', 'RESEAUX & TELECOMS', 'SYSTEMES EMBARQUES', 'PROPULSION', 'MAINTENANCE AERONAUTIQUE', 'CONCEPTION AEROSPATIALE'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='major', existing_server_default="'IA'::major")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='major',
        new_values=['IA', 'CYBERSECURITE', 'GENIE LOGICIEL', 'GENIE MECANIQUE'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='major', existing_server_default="'IA'::major")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
