"""ajout d'un champ status a la table post

Revision ID: a4cd265ef188
Revises: 3c57794a3078
Create Date: 2026-04-26 22:57:40.140274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4cd265ef188'
down_revision: Union[str, Sequence[str], None] = '3c57794a3078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    post_status_enum = postgresql.ENUM('ACTIVE', 'INACTIVE', name='poststatus')
    post_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('posts', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='poststatus'), server_default='ACTIVE', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'status')

    post_status_enum = postgresql.ENUM('ACTIVE', 'INACTIVE', name='poststatus')
    post_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
