"""ajout de plus de table pour les users

Revision ID: ca58626fe51d
Revises: 09c91926ba27
Create Date: 2026-04-12 23:01:04.640929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca58626fe51d'
down_revision: Union[str, Sequence[str], None] = '09c91926ba27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Créer manuellement les types ENUM dans PostgreSQL
    # On définit les objets ENUM
    types_enum = postgresql.ENUM('DELEGUE', 'SIMPLE', name='types')
    years_enum = postgresql.ENUM('PREMIERE_ANNEE', 'DEUXIEME_ANNEE', 'TROISIEME_ANNEE', name='years')
    
    # On les crée physiquement en base de données
    types_enum.create(op.get_bind(), checkfirst=True)
    years_enum.create(op.get_bind(), checkfirst=True)

    # 2. Supprimer les anciennes tables si nécessaire
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')

    # 3. Ajouter les colonnes standards
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('card_number', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('qr_path', sa.String(), nullable=True))

    # 4. Ajouter les colonnes ENUM (Attention aux server_default !)
    op.add_column('users', sa.Column('type', types_enum, server_default='SIMPLE', nullable=True))
    op.add_column('users', sa.Column('year', years_enum, server_default='PREMIERE_ANNEE', nullable=True))

    # 5. Créer les index
    op.create_index(op.f('ix_users_birthday'), 'users', ['birthday'], unique=False)
    op.create_index(op.f('ix_users_card_number'), 'users', ['card_number'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_type'), 'users', ['type'], unique=False)
    op.create_index(op.f('ix_users_year'), 'users', ['year'], unique=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_year'), table_name='users')
    op.drop_index(op.f('ix_users_type'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_card_number'), table_name='users')
    op.drop_index(op.f('ix_users_birthday'), table_name='users')
    op.drop_column('users', 'qr_path')
    op.drop_column('users', 'year')
    op.drop_column('users', 'type')
    op.drop_column('users', 'card_number')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'phone_number')
    op.create_table('revoked_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('revoked_tokens_pkey'))
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    # ### end Alembic commands ###
