"""ajout du champ des media sur la table message

Revision ID: ec26121880ac
Revises: ff2ab0ecc8e3
Create Date: 2026-06-16 12:00:30.160318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec26121880ac'
down_revision: Union[str, Sequence[str], None] = 'ff2ab0ecc8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'media', ['media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'media_id')
    # ### end Alembic commands ###
