"""add rfid_uuid field to user's table

Revision ID: ff2ab0ecc8e3
Revises: 2420794bd63e
Create Date: 2026-06-08 14:35:44.545630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2ab0ecc8e3'
down_revision: Union[str, Sequence[str], None] = '2420794bd63e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rfid_uid', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_rfid_uid'), 'users', ['rfid_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_rfid_uid'), table_name='users')
    op.drop_column('users', 'rfid_uid')
    # ### end Alembic commands ###
